spring.application.name=textbuddy
management.endpoints.web.exposure.include=health,info
gg.jte.developmentMode=true
spring.mvc.throw-exception-if-no-handler-found=true

textbuddy.auth.enabled=false

logging.level.root=INFO
logging.level.app.textbuddy=INFO
logging.level.org.springframework.security=INFO
